// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kijwxiumskwztbjahuhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtpand4aXVtc2t3enRiamFodWh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNjc0NTYsImV4cCI6MjA3Mjg0MzQ1Nn0.28ZL0pxC00F8AZ4roMVLXdUsNG0Gdn53gxlunscGcKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});